require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/MethodLength:
  Max: 12

Metrics/PerceivedComplexity:
  Max: 9

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Exclude:
    - 'bin/bundle'

Layout/LineLength:
  Max: 198
